// =============================================================================
// GUIVerse - Main Dashboard and Coming Soon Panel Builders
// File: src/ui/main_dashboard.sci
// =============================================================================

function ui_create_main_dashboard(fig, f_dashboard)
    // Renders the main dashboard launcher with header, continue learning card,
    // laboratory grid dynamically populated from the registry, and footer.
    
    colors = get_theme_colors();
    set(f_dashboard, "BackgroundColor", colors.bg_workspace);
    
    // 1. HEADER SECTION
    h_header_frame = uicontrol(f_dashboard, ...
        "style", "frame", ...
        "units", "normalized", ...
        "position", [0.05, 0.76, 0.90, 0.20]);
    style_control(h_header_frame, "card_frame");
    set(h_header_frame, "BackgroundColor", colors.bg_main);
    
    h_lbl_title = uicontrol(h_header_frame, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.03, 0.55, 0.94, 0.35], ...
        "string", "GUIVerse", ...
        "HorizontalAlignment", "left");
    style_control(h_lbl_title, "header");
    set(h_lbl_title, "FontSize", colors.fs_title + 5); // 18pt
    set(h_lbl_title, "BackgroundColor", colors.bg_main);
    
    h_lbl_sub = uicontrol(h_header_frame, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.03, 0.30, 0.94, 0.25], ...
        "string", "Virtual Engineering Laboratory Platform", ...
        "HorizontalAlignment", "left");
    style_control(h_lbl_sub, "label");
    set(h_lbl_sub, "FontSize", colors.fs_header + 2); // 12pt
    set(h_lbl_sub, "FontWeight", "bold");
    set(h_lbl_sub, "BackgroundColor", colors.bg_main);
    
    h_lbl_desc = uicontrol(h_header_frame, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.03, 0.05, 0.94, 0.25], ...
        "string", "Interactive simulations for Electronics and Communication Engineering.", ...
        "HorizontalAlignment", "left");
    style_control(h_lbl_desc, "label_muted");
    set(h_lbl_desc, "FontSize", colors.fs_normal + 1); // 10pt
    set(h_lbl_desc, "BackgroundColor", colors.bg_main);
    
        // 2. CONTINUE LEARNING CARD
    state = fig.user_data;
    c_learn = widgets_create_card(f_dashboard, "Continue Learning", [0.05, 0.53, 0.90, 0.20]);
    set(c_learn.frame, "BackgroundColor", colors.bg_panel);
    
    h_learn_lab = uicontrol(c_learn.frame, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.03, 0.60, 0.60, 0.22], ...
        "string", "Laboratory: Communication Laboratory", ...
        "HorizontalAlignment", "left");
    style_control(h_learn_lab, "label");
    set(h_learn_lab, "BackgroundColor", colors.bg_panel);
    set(h_learn_lab, "FontWeight", "bold");
    
    h_learn_exp = uicontrol(c_learn.frame, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.03, 0.35, 0.60, 0.22], ...
        "string", "Last Experiment: " + state.last_experiment_display, ...
        "HorizontalAlignment", "left");
    style_control(h_learn_exp, "label");
    set(h_learn_exp, "BackgroundColor", colors.bg_panel);
    set(h_learn_exp, "ForegroundColor", colors.accent_cyan);
    
    h_learn_status = uicontrol(c_learn.frame, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.03, 0.10, 0.60, 0.18], ...
        "string", "Status: Ready to resume simulation state.", ...
        "HorizontalAlignment", "left");
    style_control(h_learn_status, "label_muted");
    set(h_learn_status, "BackgroundColor", colors.bg_panel);
    
    h_resume_btn = uicontrol(c_learn.frame, ...
        "style", "pushbutton", ...
        "units", "normalized", ...
        "position", [0.75, 0.25, 0.20, 0.50], ...
        "string", "Resume", ...
        "callback", "cb_launch_comm_lab_resume()", ...
        "callback_type", 2);
    style_control(h_resume_btn, "action_button");
    set(h_resume_btn, "BackgroundColor", colors.accent_cyan);
    
    // Save handle to update dynamically later
    state.ui.dashboard_continue_experiment_label = h_learn_exp;
    
    // 3. LABORATORIES GRID
    h_grid_title = uicontrol(f_dashboard, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.05, 0.46, 0.90, 0.04], ...
        "string", "Engineering Laboratories Modules", ...
        "HorizontalAlignment", "left");
    style_control(h_grid_title, "header");
    set(h_grid_title, "FontSize", colors.fs_header + 2); // 12pt
    set(h_grid_title, "BackgroundColor", colors.bg_workspace);
    
    global g_labs_registry;
    n_labs = size(g_labs_registry);
    w_card = 0.20;
    h_card = 0.16;
    x_gap = 0.03;
    
    for i = 1:n_labs
        lab = g_labs_registry(i);
        
        col = modulo(i - 1, 4) + 1;
        row = 2 - floor((i - 1) / 4); // row 2 is top, row 1 is bottom
        
        x_pos = 0.05 + (col - 1) * (w_card + x_gap);
        y_pos = 0.08 + (row - 1) * (h_card + 0.04);
        
        h_lab_frame = uicontrol(f_dashboard, ...
            "style", "frame", ...
            "units", "normalized", ...
            "position", [x_pos, y_pos, w_card, h_card]);
        style_control(h_lab_frame, "card_frame");
        set(h_lab_frame, "BackgroundColor", colors.bg_panel);
        
        h_lab_name = uicontrol(h_lab_frame, ...
            "style", "text", ...
            "units", "normalized", ...
            "position", [0.05, 0.62, 0.90, 0.30], ...
            "string", lab.name, ...
            "HorizontalAlignment", "center");
        style_control(h_lab_name, "panel_header");
        set(h_lab_name, "BackgroundColor", colors.bg_panel);
        
        h_lab_status = uicontrol(h_lab_frame, ...
            "style", "text", ...
            "units", "normalized", ...
            "position", [0.05, 0.40, 0.90, 0.20], ...
            "string", lab.status, ...
            "HorizontalAlignment", "center");
        style_control(h_lab_status, "label_muted");
        set(h_lab_status, "BackgroundColor", colors.bg_panel);
        
        if lab.status == "Production Ready" then
            set(h_lab_status, "ForegroundColor", colors.accent_green);
            set(h_lab_status, "FontWeight", "bold");
            
            h_action = uicontrol(h_lab_frame, ...
                "style", "pushbutton", ...
                "units", "normalized", ...
                "position", [0.15, 0.08, 0.70, 0.28], ...
                "string", "Launch", ...
                "callback", lab.callback, ...
                "callback_type", 2);
            style_control(h_action, "action_button");
            set(h_action, "BackgroundColor", colors.accent_green);
        else
            set(h_lab_status, "ForegroundColor", colors.text_muted);
            
            // Generate a details callback string dynamically
            cb_str = sprintf("cb_launch_coming_soon("'%s'")", lab.name);
            h_action = uicontrol(h_lab_frame, ...
                "style", "pushbutton", ...
                "units", "normalized", ...
                "position", [0.15, 0.08, 0.70, 0.28], ...
                "string", "Coming Soon", ...
                "callback", cb_str, ...
                "callback_type", 2);
            style_control(h_action, "sidebar_button");
            set(h_action, "BackgroundColor", colors.bg_input);
            set(h_action, "ForegroundColor", colors.text_muted);
        end
    end
    
    // 4. FOOTER
    h_footer = uicontrol(f_dashboard, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.05, 0.01, 0.90, 0.03], ...
        "string", "Version 1.0 // Production Modules: Communication Laboratory", ...
        "HorizontalAlignment", "center");
    style_control(h_footer, "label_muted");
    set(h_footer, "BackgroundColor", colors.bg_workspace);
    
    fig.user_data = state;
endfunction

function ui_update_main_dashboard(state)
    // Synchronizes the Continue Learning card label with the latest active experiment
    h_lbl = state.ui.dashboard_continue_experiment_label;
    if ~isempty(h_lbl) & is_valid_handle(h_lbl) then
        set(h_lbl, "string", "Last Experiment: " + state.last_experiment_display);
    end
endfunction

function ui_create_coming_soon(fig, f_coming_soon)
    // Renders the clean planned laboratory description card with a Back button.
    
    colors = get_theme_colors();
    set(f_coming_soon, "BackgroundColor", colors.bg_workspace);
    
    // Center card
    h_card_frame = uicontrol(f_coming_soon, ...
        "style", "frame", ...
        "units", "normalized", ...
        "position", [0.20, 0.20, 0.60, 0.60]);
    style_control(h_card_frame, "card_frame");
    set(h_card_frame, "BackgroundColor", colors.bg_panel);
    
    // Icon label / placeholder
    h_icon = uicontrol(h_card_frame, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.10, 0.72, 0.80, 0.15], ...
        "string", "[ ~ ]", ...
        "HorizontalAlignment", "center");
    style_control(h_icon, "header");
    set(h_icon, "FontSize", colors.fs_title + 7); // 20pt
    set(h_icon, "BackgroundColor", colors.bg_panel);
    
    // Lab Name Title
    h_title = uicontrol(h_card_frame, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.05, 0.58, 0.90, 0.12], ...
        "string", "Laboratory Module", ...
        "HorizontalAlignment", "center");
    style_control(h_title, "header");
    set(h_title, "FontSize", colors.fs_title + 1); // 14pt
    set(h_title, "BackgroundColor", colors.bg_panel);
    
    // Message Edit box (multiline clean notice)
    h_msg = uicontrol(h_card_frame, ...
        "style", "edit", ...
        "units", "normalized", ...
        "position", [0.10, 0.25, 0.80, 0.30], ...
        "max", 2, ...
        "min", 0, ...
        "enable", "off", ...
        "string", ["This laboratory is planned for a future release.";
                   "";
                   "Only the Communication Laboratory is available in Version 1."], ...
        "HorizontalAlignment", "center");
    style_control(h_msg, "label");
    set(h_msg, "FontSize", colors.fs_normal + 2); // 11pt
    set(h_msg, "BackgroundColor", colors.bg_panel);
    set(h_msg, "ForegroundColor", colors.text_primary);
    
    // Back button
    h_back_btn = uicontrol(h_card_frame, ...
        "style", "pushbutton", ...
        "units", "normalized", ...
        "position", [0.38, 0.08, 0.24, 0.10], ...
        "string", "Back", ...
        "callback", "cb_coming_soon_back()", ...
        "callback_type", 2);
    style_control(h_back_btn, "action_button");
    set(h_back_btn, "BackgroundColor", colors.accent_cyan);
    
    // Store title handle to state so we can customize the text when opening
    state = fig.user_data;
    state.ui.coming_soon_title = h_title;
    fig.user_data = state;
endfunction
