// =============================================================================
// GUIVerse - Sidebar Navigation Panel
// File: src/ui/sidebar.sci
// =============================================================================

function ui_create_sidebar(fig, sidebar_panel)
    // Instantiates the sidebar panel widgets, builds the module navigation list,
    // and binds callbacks to switch between panels.
    // Inputs:
    //   fig: graphic handle of the main window
    //   sidebar_panel: graphic handle of the sidebar container frame
    
    colors = get_theme_colors();
    set(sidebar_panel, "BackgroundColor", colors.bg_main);
    
    // Retrieve state
    state = fig.user_data;
    
    // Add Branding Header
    h_title = uicontrol(sidebar_panel, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.05, 0.95, 0.90, 0.035], ...
        "string", "GUIVerse", ...
        "HorizontalAlignment", "center");
    style_control(h_title, "header");
    set(h_title, "BackgroundColor", colors.bg_main);
    
    // Add Subtitle
    h_sub = uicontrol(sidebar_panel, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.05, 0.92, 0.90, 0.025], ...
        "string", "Digital Comm Lab v1.0", ...
        "HorizontalAlignment", "center");
    style_control(h_sub, "label_muted");
    set(h_sub, "BackgroundColor", colors.bg_main);
    
    // Parallel arrays defining the layout items
    items_type = [ ...
        "exit", "home", ...
        "separator", ...
        "header", "button", ...
        "separator", ...
        "header", "button", "button", ...
        "separator", ...
        "header", "button", "button", ...
        "separator", ...
        "header", "button", "button", ...
        "separator", ...
        "header", "disabled", "disabled", "disabled", "disabled", "disabled", "disabled", "disabled", "disabled", "disabled", "disabled" ...
    ];
    
    items_text = [ ...
        "<- Exit to Launcher", "  Home Dashboard", ...
        "", ...
        "Source Generation", "  Analog Signal Gen", ...
        "", ...
        "Sampling", "  Uniform Sampling", "  Whittaker Recon", ...
        "", ...
        "Quantization", "  Uniform Quantizer", "  Non-uniform Quant", ...
        "", ...
        "Encoding", "  PCM Encoder", "  Serialized PCM Link", ...
        "", ...
        "Future Roadmap", "  Delta Modulation", "  Adaptive DM", "  Differential PCM", "  ASK Modulation", "  FSK Modulation", "  PSK Modulation", "  QPSK Modulation", "  QAM Modulation", "  Matched Filter", "  BER Analysis" ...
    ];
    
    items_target = [ ...
        "", "home", ...
        "", ...
        "", "signal_generator", ...
        "", ...
        "", "sampling_uniform", "sampling_recon", ...
        "", ...
        "", "quant_uniform", "quant_nonuniform", ...
        "", ...
        "", "pcm_encoder", "pcm_serialized", ...
        "", ...
        "", "", "", "", "", "", "", "", "", "", "" ...
    ];
    
    n_items = size(items_type, "*");
    y_cursor = 0.89;
    spacing = 0.027;
    btn_height = 0.023;
    
    for i = 1:n_items
        itype = items_type(i);
        itext = items_text(i);
        itarget = items_target(i);
        
        if itype == "exit" then
            h_btn = uicontrol(sidebar_panel, ...
                "style", "pushbutton", ...
                "units", "normalized", ...
                "position", [0.05, y_cursor - 0.028, 0.90, 0.028], ...
                "string", itext, ...
                "HorizontalAlignment", "center", ...
                "callback", "cb_exit_to_launcher()", ...
                "callback_type", 2);
            style_control(h_btn, "action_button");
            set(h_btn, "BackgroundColor", colors.accent_red);
            y_cursor = y_cursor - 0.032;
            
        elseif itype == "separator" then
            y_cursor = y_cursor - 0.003;
            h_sep = uicontrol(sidebar_panel, ...
                "style", "frame", ...
                "units", "normalized", ...
                "position", [0.05, y_cursor - 0.002, 0.90, 0.002]);
            style_control(h_sep, "card_frame");
            set(h_sep, "BackgroundColor", colors.bg_input);
            y_cursor = y_cursor - 0.008;
            
        elseif itype == "header" then
            y_cursor = y_cursor - 0.003;
            h_lbl = uicontrol(sidebar_panel, ...
                "style", "text", ...
                "units", "normalized", ...
                "position", [0.05, y_cursor - 0.020, 0.90, 0.020], ...
                "string", itext, ...
                "HorizontalAlignment", "left");
            style_control(h_lbl, "label_muted");
            set(h_lbl, "BackgroundColor", colors.bg_main);
            set(h_lbl, "ForegroundColor", colors.accent_cyan);
            set(h_lbl, "FontWeight", "bold");
            set(h_lbl, "FontSize", colors.fs_small);
            y_cursor = y_cursor - 0.024;
            
        elseif itype == "home" | itype == "button" then
            h_btn = uicontrol(sidebar_panel, ...
                "style", "pushbutton", ...
                "units", "normalized", ...
                "position", [0.05, y_cursor - btn_height, 0.90, btn_height], ...
                "string", itext, ...
                "HorizontalAlignment", "left", ...
                "user_data", itarget, ...
                "callback", "cb_sidebar_click()", ...
                "callback_type", 2);
                
            if itarget == state.active_module then
                style_control(h_btn, "sidebar_active_button");
            else
                style_control(h_btn, "sidebar_button");
                set(h_btn, "BackgroundColor", colors.bg_main);
            end
            
            // Save handle to state dynamically
            state = ui_set_sidebar_button(state, itarget, h_btn);
            y_cursor = y_cursor - spacing;
            
        elseif itype == "disabled" then
            h_btn = uicontrol(sidebar_panel, ...
                "style", "pushbutton", ...
                "units", "normalized", ...
                "position", [0.05, y_cursor - btn_height, 0.90, btn_height], ...
                "string", itext + " (Soon)", ...
                "HorizontalAlignment", "left", ...
                "enable", "off");
            style_control(h_btn, "sidebar_button");
            set(h_btn, "BackgroundColor", colors.bg_main);
            set(h_btn, "ForegroundColor", colors.text_dark); // distinct dark gray for roadmap items
            y_cursor = y_cursor - spacing;
        end
    end
    
    fig.user_data = state;
endfunction
