// =============================================================================
// CommVerse - Top Toolbar Panel
// File: src/ui/toolbar.sci
// =============================================================================

function ui_create_toolbar(fig, toolbar_panel)
    // Instantiates top control panel options.
    // Inputs:
    //   fig: graphic handle of the main window
    //   toolbar_panel: graphic handle of the toolbar container frame
    
    colors = get_theme_colors();
    
    // Set toolbar panel frame background to match main background
    set(toolbar_panel, "BackgroundColor", colors.bg_main);
    
    // Left side: Branding text
    h_title = uicontrol(toolbar_panel, ...
        "style", "text", ...
        "units", "normalized", ...
        "position", [0.02, 0.2, 0.4, 0.6], ...
        "string", "CommVerse // Complete Digital Communication Laboratory", ...
        "HorizontalAlignment", "left");
    style_control(h_title, "header");
    // Ensure the text background matches the toolbar panel background
    set(h_title, "BackgroundColor", colors.bg_main);
    
    // Right side: Quick Action Buttons
    // 1. Reset Button
    h_reset = uicontrol(toolbar_panel, ...
        "style", "pushbutton", ...
        "units", "normalized", ...
        "position", [0.65, 0.2, 0.1, 0.6], ...
        "string", "Reset System", ...
        "user_data", "reset", ...
        "callback", "cb_toolbar_action()", ...
        "callback_type", 2);
    style_control(h_reset, "action_button");
    set(h_reset, "BackgroundColor", colors.accent_red); // Mark reset in red
    
    // 2. Export Report Button
    h_export = uicontrol(toolbar_panel, ...
        "style", "pushbutton", ...
        "units", "normalized", ...
        "position", [0.77, 0.2, 0.1, 0.6], ...
        "string", "Export Report", ...
        "user_data", "export", ...
        "callback", "cb_toolbar_action()", ...
        "callback_type", 2);
    style_control(h_export, "action_button");
    
    // 3. Theme Toggle Button (Stretch Goal)
    h_theme = uicontrol(toolbar_panel, ...
        "style", "pushbutton", ...
        "units", "normalized", ...
        "position", [0.89, 0.2, 0.09, 0.6], ...
        "string", "Toggle Theme", ...
        "user_data", "theme", ...
        "callback", "cb_toolbar_action()", ...
        "callback_type", 2);
    style_control(h_theme, "action_button");
    set(h_theme, "BackgroundColor", colors.bg_input);
    set(h_theme, "ForegroundColor", colors.text_primary);
    
    // Save to global state handles if needed (e.g. for disabling/enabling)
    state = fig.user_data;
    state.ui.toolbar_buttons = struct(...
        "reset", h_reset, ...
        "export", h_export, ...
        "theme", h_theme ...
    );
    fig.user_data = state;
endfunction
