// =============================================================================
// GUIVerse - Global State Management & Map Helper Utilities
// File: src/state/state.sci
// =============================================================================

function state = init_global_state()
    // Returns a default initialized global state structure.
    // Uses lists and vectors for dynamic panels/buttons lookup to avoid
    // unsupported structure dynamic indexing in some Scilab versions.
    
    state = struct(...
        "active_module", "home", ...
        "theme", "dark", ...
        "last_experiment", "quant_uniform", ...
        "last_experiment_display", "Uniform Quantizer", ...
        "pipeline_names", ["signal", "sampling", "quantization", "pcm", "linecoding", "modulation", "channel", "receiver", "recovered"], ...
        "pipeline_status", ["OK", "OK", "OK", "OK", "OK", "OK", "OK", "OK", "OK"], ...
        "params", struct(...
            "signal", struct(...
                "type", "sine", ...
                "amp", 1.0, ...
                "freq", 5.0, ...
                "phase", 0.0, ...
                "duty_cycle", 0.5, ...
                "bit_rate", 10.0, ...
                "import_file", "" ...
            ), ...
            "sampling", struct(...
                "fs", 40.0, ...
                "method", "ideal", ...
                "reconstruct_fc", 15.0 ...
            ), ...
            "quantization", struct(...
                "levels", 8, ...
                "type", "uniform_midrise", ...
                "mu", 255.0, ...
                "A", 87.6 ...
            ), ...
            "pcm", struct(...
                "bits_per_sample", 3 ...
            ), ...
            "linecoding", struct(...
                "type", "nrz_l" ...
            ), ...
            "modulation", struct(...
                "type", "bpsk", ...
                "fc", 100.0 ...
            ), ...
            "channel", struct(...
                "snr", 15.0, ...
                "attenuation", 1.0 ...
            ), ...
            "receiver", struct(...
                "filter_type", "matched", ...
                "decision_type", "threshold" ...
            )...
        ), ...
        "data", struct(...
            "time", [], ...
            "analog_waveform", [], ...
            "sampled_time", [], ...
            "sampled_waveform", [], ...
            "quantized_waveform", [], ...
            "tx_bits", [], ...
            "linecode_time", [], ...
            "linecode_waveform", [], ...
            "modulated_time", [], ...
            "modulated_waveform", [], ...
            "rx_time", [], ...
            "rx_waveform", [], ...
            "demodulated_bits", [], ...
            "recovered_time", [], ...
            "recovered_waveform", [], ...
            "sqnr", 0.0, ...
            "ber", 0.0, ...
            "bandwidth", 0.0, ...
            "power", 0.0, ...
            "bit_rate_actual", 10.0, ...
            "spectral_efficiency", 0.0 ...
        ), ...
        "ui", struct(...
            "fig", [], ...
            "sidebar_panel", [], ...
            "toolbar_panel", [], ...
            "workspace_panel", [], ...
            "education_panel", [], ...
            "status_panel", [], ...
            "module_names", ["home", "signal_generator", "sampling", "quantization", "pcm", ...
                             "linecoding", "modulation", "noise", "receiver", "ber", ...
                             "eye", "constellation", "comparison", ...
                             "sampling_uniform", "sampling_recon", ...
                             "quant_uniform", "quant_nonuniform", ...
                             "pcm_encoder", "pcm_serialized"], ...
            "module_panels", list(), ...
            "sidebar_buttons", list(), ...
            "pipeline_block_names", ["signal", "sampling", "quantization", "pcm", "linecoding", "modulation", "channel", "receiver", "recovered"], ...
            "pipeline_block_handles", list(), ...
            "dashboard_metrics", [], ...
            "status_bar", list() ...
        )...
    );
    
    // Pre-initialize lists with empty matrices for all modules
    for i = 1:size(state.ui.module_names, "*")
        state.ui.module_panels(i) = [];
        state.ui.sidebar_buttons(i) = [];
    end
    // Pre-initialize block handles list
    for i = 1:size(state.ui.pipeline_block_names, "*")
        state.ui.pipeline_block_handles(i) = [];
    end
    // Status bar list handles
    // 1: status_label, 2: snr_label, 3: ber_label, 4: sqnr_label, 5: bitrate_label
    for i = 1:5
        state.ui.status_bar(i) = [];
    end
endfunction

// --- MULTI-PLATFORM COMPATIBLE MAP HELPERS ---

function flag = struct_isfield(st, field_name)
    // Checks if a field exists in a Scilab structure.
    names = fieldnames(st);
    flag = or(names == field_name);
endfunction

function h = ui_get_module_panel(state, name)
    // Retrieves a module's container panel handle by string name
    resolved_name = name;
    if name == "sampling_uniform" | name == "sampling_recon" then
        resolved_name = "sampling";
    elseif name == "quant_uniform" | name == "quant_nonuniform" then
        resolved_name = "quantization";
    elseif name == "pcm_encoder" | name == "pcm_serialized" then
        resolved_name = "pcm";
    end
    
    idx = find(state.ui.module_names == resolved_name);
    if isempty(idx) then
        h = [];
    else
        h = state.ui.module_panels(idx);
    end
endfunction

function state = ui_set_module_panel(state, name, h_panel)
    // Stores a module's container panel handle
    resolved_name = name;
    if name == "sampling_uniform" | name == "sampling_recon" then
        resolved_name = "sampling";
    elseif name == "quant_uniform" | name == "quant_nonuniform" then
        resolved_name = "quantization";
    elseif name == "pcm_encoder" | name == "pcm_serialized" then
        resolved_name = "pcm";
    end
    
    idx = find(state.ui.module_names == resolved_name);
    if ~isempty(idx) then
        state.ui.module_panels(idx) = h_panel;
    end
endfunction

function h = ui_get_sidebar_button(state, name)
    // Retrieves a sidebar button handle by string name
    idx = find(state.ui.module_names == name);
    if isempty(idx) then
        h = [];
    else
        h = state.ui.sidebar_buttons(idx);
    end
endfunction

function state = ui_set_sidebar_button(state, name, h_btn)
    // Stores a sidebar button handle
    idx = find(state.ui.module_names == name);
    if ~isempty(idx) then
        state.ui.sidebar_buttons(idx) = h_btn;
    end
endfunction

function h = ui_get_pipeline_block(state, name)
    // Retrieves a dashboard block button handle by string name
    idx = find(state.ui.pipeline_block_names == name);
    if isempty(idx) then
        h = [];
    else
        h = state.ui.pipeline_block_handles(idx);
    end
endfunction

function state = ui_set_pipeline_block(state, name, h_btn)
    // Stores a dashboard block button handle
    idx = find(state.ui.pipeline_block_names == name);
    if ~isempty(idx) then
        state.ui.pipeline_block_handles(idx) = h_btn;
    end
endfunction

function status_val = state_get_pipeline_status(state, stage_name)
    // Retrieves the execution status ('OK' | 'PENDING' | 'ERROR') of a pipeline stage
    idx = find(state.pipeline_names == stage_name);
    if isempty(idx) then
        status_val = "PENDING";
    else
        status_val = state.pipeline_status(idx);
    end
endfunction

function state = state_set_pipeline_status(state, stage_name, status_str)
    // Sets the execution status of a pipeline stage
    idx = find(state.pipeline_names == stage_name);
    if ~isempty(idx) then
        state.pipeline_status(idx) = status_str;
    end
endfunction

function update_pipeline_status(stage_name, status_str)
    // Updates a specific stage execution flag in the pipeline and saves it.
    fig = find_main_figure();
    if isempty(fig) then return; end
    state = fig.user_data;
    
    state = state_set_pipeline_status(state, stage_name, status_str);
    fig.user_data = state;
endfunction
